version: '3.8'

services:
  ssh-server:
    image: ssh-server:latest
    build:
      context: .
      dockerfile: ${PWD}/Dockerfile
      
    ports:
      - "22:22"
    
    volumes:
      - ssh-volume:/home/sshuser/shared
      - v1:/home/sshuser/Videos
      - ${PWD}/authorized_keys:/home/sshuser/.ssh/authorized_keys

    command: [ "/usr/sbin/sshd", "-D" ]

volumes:
  ssh-volume:
    external: true

  v1:
    external: true

  v2:
    external: true