version: '3.5'

services:
  db:
    image: postgres:10-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data:consistent
    secrets:
      - db_user
      - db_password
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - database

volumes:
  postgres-data:
    external: true
    name: 'postgres-data'

secrets:
  db_user:
    file: ./.secrets/db.user
  db_password:
    file: ./.secrets/db.password

networks:
  database:
    external: true
    name: database
