version: '3.6'

services:
  runner:
    image: gitlab/gitlab-runner:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '2048M'

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-config:/etc/gitlab-runner

volumes:
  runner-config:
