version: '3.5'

services:
  mysql:
    image: 'mysql:8.0'
    secrets:
      - db_db_name
      - db_user
      - db_password
      - db_root_password

    # Should change root password to different file
    environment:
      - MYSQL_DATABASE_FILE=/run/secrets/db_db_name
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password

    # volumes:
      # - mysql_data:/var/lib/mysql

    networks:
      - database
    
    ports:
      - "3306:3306"

secrets:
  db_db_name:
    file: .secrets/db.db_name
  db_user:  
    file: .secrets/db.user
  db_password:
    file: .secrets/db.password
  db_root_password:
    file: .secrets/db.root_password

volumes:
  mysql_data:
    name: mysql-data
    external: true

networks:
  database:
    name: database
    external: true
