version: '3.5'
services:
  auth:
    image: 'jboss/keycloak:4.2.1.Final'
    env_file:
      - ./secrets.env
    depends_on:
      - postgres
    networks:
      database:
      proxy:

networks:
  database:
    external: true
    name: database
  proxy:
    external: true
    name: nginx-proxy
