version: '3.5'
services:
  nginx:
    image: coditware:nginx-alpine

    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      
      - mode: host
        protocol: tcp
        published: 443
        target: 443
        
    networks:
      - proxy

    secrets:
      - ssl.key
      - ssl.crt

networks:
  proxy:
    external: true
    name: nginx-proxy

secrets:
  ssl.key:
    file: .secrets/test.key
  ssl.crt:
    file: .secrets/test.crt
