version: '3.5'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    deploy:
      resources:
        limits:
          memory: '2048M'
    volumes:
      - var-opt:/var/opt/gitlab
      - etc:/etc/gitlab
      - var-log:/var/log/gitlab

volumes:
  var-opt:
  var-log:
  etc:
